apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-boas-vindas


images:
- name: app-boas-vindas
  newName: nandocloud/app-boas-vindas
  newTag: 5a6049cb09f888c8c4b620a8f694888d0c37ccb1
- name: app-site
  newName: nandocloud/app-boas-vindas
  newTag: 54c41a705157a0bd9405a494fa040ed160c9e1c8
