apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-boas-vindas


images:
- name: app-boas-vindas
  newName: nandocloud/app-boas-vindas
  newTag: 5a6049cb09f888c8c4b620a8f694888d0c37ccb1
- name: app-site
  newName: nandocloud/app-boas-vindas
  newTag: d0e1d643b65f06497e73fad527315df2e4f80abc
